### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by GioviQ**

### CODE REVIEW

**Comment by GioviQ** [comment]
> Why did you delete AssemblyInfo and removed most of the configuration?

I am expert in .NET Framework, but not much in .NET standard / core project and during migration Visual Studio warning me about duplicate information in AssemblyInfo. I discovered that this is not mandatory so I deleted. Build, test and all works. If you release a new package, you have to restore some info.

**Comment by maurosampietro** [comment]
Deleting AssemblyInfo prevent AppVeyor to work correctly and thus a new package to be correctly released on nuget.

In general your edits may be good for your needs but don't guarantee (may actually break) building the project for .NET Framework.

If you need to target .Net Standard, please consider converting the .csproj file to a MultiTargeting  project.

.NetFramework build cannot be dropped.

Also, the file package.config you deleted is needed to download specific packages from nuget.

**Comment by GioviQ** [comment]
I migrate package.config to package reference https://docs.microsoft.com/it-it/nuget/consume-packages/package-references-in-project-files

**Comment by Reapism** [comment]
> .NetFramework build cannot be dropped. 

Why is that the case?  The project itself doesn't have any .NET framework dependencies so why choose the least compatible microsoft framework especially for an API? As an API, you would want to target many more users. The change is also non breaking. 

I created a PR to remove .NET Framework entirely.  #8 

I'm not sure if AppVeyor will have issues generating the package unless its properly configured to not rely on .NET Framework.

**Pull request closed without merging**
