### PR TITLE
Adding lots of tests for null projection

### PR DESCRIPTION
**Pull request by hermanlindner**
Adding a lot of tests to the solution for nullable projection

### CODE REVIEW

**Comment by maurosampietro** [comment]
Hi Herman,

Had some time to work on UltraMapper recently.
I integrated your projection test in the main project.
Most of the tests pass. Just the following 4 don't pass at the moment:

    CustomExternalConverter_MapTestPropHasValue
    CustomExternalConverter_MapTestPropDefault
    CustomExternalConverter_MapTestChain1Null
    CustomExternalConverter_MapTestChain2Null

Please take a look at the develop branch, compile it and let me have your feedback.
Take also a look into the tests, it was just configuration.

**Comment by hermanlindner** [comment]
Hi Mauro,

I am joyed to know that my work is being looked at.
I did do a fork of your project also, so maybe on the fork these problems
might have already been resolved.

You say that these tests are now failing on the development branch right?
Will look at the differences between the fork and the development branch.

And update you on what might cause these problems.

Later this weekend I might have some time for that.

Kind regards,

Herman

**Comment by hermanlindner** [comment]
Hi Mauro,

I took a look again at what I did on my fork.

I now remember that I did not got it working with just overloading
the MapMember method because there were going to be too many conflicts that
it cannot automatically resolve which
overload was intended.

So in the fork I ended up up with multiple overloads for 3 different named
mapping methods:

MapMemberNullProjection  (Which can map from non null field on a projection
and make the type nullable,  because earlier types in projection path could
be null.)
MapMember (regular member mapping, also still projection which does not
include the specific case mentioned above)
MapConditionalMember (Which is used for conditional mapping).

I now do remember I could not get it to properly work when
MapMemberNullProjection had the same name as MapMember.

If you agree that I also will have these 3 Mapmember method names in the
development branch, I can get that part of the code working (but then with
overloads for these 3 different named methods).
You could further investigate my fork to determine if this is what you
could live with on your dev branch.

I will wait for you to reply, before I create a branch from the dev branch
to make these methods work.

So please let me know if this is agreeable to you.

Kind regards,

Herman

ps the fork resides here:
https://github.com/hermanlindner/UltraMapper-variant-by-Herman

ps2:
When I clone the sources of your master branch, on my local machine I do
get failing tests still:
  CollectionTests.PrimitiveCollection is failing with  Assert.IsTrue
failed.
  DirectMappings.UnmaterializedMultidimensionalArray is failing with

  Message:
    Assert.IsTrue failed.

  Stack Trace:
    DirectMappings.UnmaterializedMultidimensionalArray() line 281

  Standard Output:
    System.Collections.Generic.List`1[System.Int32]
    System.Collections.Generic.List`1[System.Int32]
    System.Collections.Generic.List`1[System.Int32]
    System.Collections.Generic.List`1[System.Int32]
    System.Collections.Generic.List`1[System.Int32]
    System.Collections.Generic.List`1[System.Int32]
    System.Collections.Generic.List`1[System.Int32]
    System.Collections.Generic.List`1[System.Int32]
    System.Collections.Generic.List`1[System.Int32]
    System.Collections.Generic.List`1[System.Int32]
    System.Collections.Generic.List`1[System.Int32[]]

ps3:
Are you intending to get .Net 8 as a target for the ultramapper soon?

**Comment by maurosampietro** [comment]
Hi,In those cases named-params solve the issue. And no other overload is needed. Just write converter: before the converter fund in the map member method. You can find an example in my update code base. Developer branch.On 24 Nov 2023, at 11:55, hermanlindner ***@***.***> wrote:﻿
Hi Mauro,



I took a look again at what I did on my fork.



I now remember that I did not got it working with just overloading

the MapMember method because there were going to be too many conflicts that

it cannot automatically resolve which

overload was intended.



So in the fork I ended up up with multiple overloads for 3 different named

mapping methods:



MapMemberNullProjection  (Which can map from non null field on a projection

and make the type nullable,  because earlier types in projection path could

be null.)

MapMember (regular member mapping, also still projection which does not

include the specific case mentioned above)

MapConditionalMember (Which is used for conditional mapping).



I now do remember I could not get it to properly work when

MapMemberNullProjection had the same name as MapMember.



If you agree that I also will have these 3 Mapmember method names in the

development branch, I can get that part of the code working (but then with

overloads for these 3 different named methods).

You could further investigate my fork to determine if this is what you

could live with on your dev branch.



I will wait for you to reply, before I create a branch from the dev branch

to make these methods work.



So please let me know if this is agreeable to you.



Kind regards,



Herman



ps the fork resides here:

https://github.com/hermanlindner/UltraMapper-variant-by-Herman



ps2:

When I clone the sources of your master branch, on my local machine I do

get failing tests still:

  CollectionTests.PrimitiveCollection is failing with  Assert.IsTrue

failed.

  DirectMappings.UnmaterializedMultidimensionalArray is failing with



  Message:

    Assert.IsTrue failed.



  Stack Trace:

    DirectMappings.UnmaterializedMultidimensionalArray() line 281



  Standard Output:

    System.Collections.Generic.List`1[System.Int32]

    System.Collections.Generic.List`1[System.Int32]

    System.Collections.Generic.List`1[System.Int32]

    System.Collections.Generic.List`1[System.Int32]

    System.Collections.Generic.List`1[System.Int32]

    System.Collections.Generic.List`1[System.Int32]

    System.Collections.Generic.List`1[System.Int32]

    System.Collections.Generic.List`1[System.Int32]

    System.Collections.Generic.List`1[System.Int32]

    System.Collections.Generic.List`1[System.Int32]

    System.Collections.Generic.List`1[System.Int32[]]



ps3:

Are you intending to get .Net 8 as a target for the ultramapper soon?





On Wed, Nov 15, 2023 at 6:05 PM Mauro Sampietro ***@***.***>

wrote:

**Pull request closed without merging**
